### ISSUE TITLE
Where's the toolkit.jar?

### ISSUE THREAD

**Issue by RandyHarryTheGoanimate** [ennuo/toolkit#16]
I can't find the toolkit.jar. Please help!

**Comment by RandyHarryTheGoanimate** [comment]
I CAN'T GET THE toolkit.jar? WHY!

**Comment by Avellea** [comment]
I could not find a pre-built binary. You can build it by first installing the JDK and Maven, then cloning the repo and building it.

**Comment by users-things** [comment]
i made a re release with the .jar I got before [https://github.com/users-things/toolkit-re-release/releases/tag/archives](url)

**Comment by ennuo** [comment]
The latest commit on main has been added to releases.
https://github.com/ennuo/toolkit/releases/tag/Release
