### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Fewnity** [ennuo/toolkit#26]
When I'm trying to launch the toolkit, I'm getting "A Java Exception has occured".

I have Java 17.0.9

How I can fix this?
Thanks

**Comment by Fewnity** [comment]
I tried the new version, It's still crashing. I have jdk-20.

**Comment by ennuo** [comment]
Can't particularly say without any more information.

Is that the only error displayed? Multiple installs of Java on your system?

**Comment by Fewnity** [comment]
Yeah it's the only error displayed... The title of the error dialog is "Java Virtual Machine Launcher".

On this computer I just have Java JDK 20 and jre-1.8 (latest version of java 8)

**Comment by ennuo** [comment]
Does the Java 8 runtime have precedence over the 20 JDK then?

Running with the wrong version generally seems to be the cause of that specific issue.

Try checking the version of Java that's being used in the path, or launching through command line.

**Comment by Fewnity** [comment]
Ok when I type `java -jar toolkit-0.1.jar` it's working.
And when type `java -version` i have `java version "20.0.1"`.
I thought `java -jar toolkit-0.1.jar was the same result has double clicking on the .jar file. Weird but at least it's working like that. Maybe double clicking uses Java 8?

Just a question, any plans about PSP version support?

**Comment by ennuo** [comment]
Yeah, seems so. 

As for PSP support, it's not currently planned at the moment, although I've considered it.

**Comment by Fewnity** [comment]
Ok, thanks for responding.
