### ISSUE TITLE
Toolkit is broken, maybe my Java Version..

### ISSUE THREAD

**Issue by DamianBossPL** [ennuo/toolkit#7]
I load up the toolkit with Java SDK 17.0.1, load my bigfart11 (LBP1 Profile) I try and edit a level slot and it shows a blank window. Same thing with exiting! Title is 'Pending Changes' with a blank window. It is probably my Java version but I don't know.

**Comment by ennuo** [comment]
The Darcula theme doesn't play nicely with any version of Java greater than 11.

**Comment by DamianBossPL** [comment]
So I just use a version under 11 like Java 8? Right?

**Comment by DamianBossPL** [comment]
Ok I got it working now with Java 8! Thank you.
